### ISSUE TITLE
Consider doing a maven release

### ISSUE THREAD

**Issue by mpenet** [eerohele/pp#4]
First, thanks for the lib, it's great!

We need it to be in a maven repo for our non-tools.deps consumers. I know I could vendor it, but I'd rather avoid that if possible. Do you think you could consider doing this?

**Comment by eerohele** [comment]
Definitely. 👍🏻 I'll do it later today or tomorrow.

**Comment by eerohele** [comment]
pp should now be available in Clojars at:

```clojure
me.flowthing/pp {:mvn/version "2023-10-05.5"}
```

If you try it out, can you let me know whether it works OK for you? Wouldn't be the first time I've botched the initial Maven release...

**Comment by mpenet** [comment]
It works fine! Thanks
